services:
  - type: web
    name: b2x-hp
    env: static
    buildCommand: echo "no build needed"
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*.css
        name: Cache-Control
        value: public, max-age=86400
      - path: /*.js
        name: Cache-Control
        value: public, max-age=86400
    routes:
      - type: rewrite
        source: /company
        destination: /company.html
      - type: rewrite
        source: /contact
        destination: /contact.html
